PREVIEW_PANEL_WIDTH = 200
PREVIEW_PANEL_HEIGHT = 188
_PREVIEW_MARGIN_V = 20
_PREVIEW_HEADER = 18
_PREVIEW_SPACING = 6
PREVIEW_CONTENT_HEIGHT = 120
ACCOUNT_TOP_ROW_HEIGHT = 62
ACCOUNT_BIO_HEIGHT = (
    PREVIEW_PANEL_HEIGHT
    - _PREVIEW_MARGIN_V
    - _PREVIEW_HEADER
    - _PREVIEW_SPACING
    - ACCOUNT_TOP_ROW_HEIGHT
    - _PREVIEW_SPACING
)

FRIENDS_PANEL_WIDTH = 308
FRIEND_CARD_WIDTH = 76
FRIEND_CARD_HEIGHT = 110
FRIEND_FOOTER_HEIGHT = 54
FRIEND_IMAGE_HEIGHT = FRIEND_CARD_HEIGHT - FRIEND_FOOTER_HEIGHT
FRIEND_GRID_COLUMNS = 3
