PREVIEW_PANEL_WIDTH = 200
PREVIEW_PANEL_HEIGHT = 188
_PREVIEW_MARGIN_V = 20
_PREVIEW_HEADER = 18
_PREVIEW_SPACING = 6
PREVIEW_CONTENT_HEIGHT = 120
ACCOUNT_TOP_ROW_HEIGHT = 62
ACCOUNT_BIO_HEIGHT = PREVIEW_PANEL_HEIGHT - _PREVIEW_MARGIN_V - _PREVIEW_HEADER - _PREVIEW_SPACING - ACCOUNT_TOP_ROW_HEIGHT - _PREVIEW_SPACING
FRIENDS_PANEL_WIDTH = 308
FRIEND_CARD_WIDTH = 76
FRIEND_CARD_HEIGHT = 110
FRIEND_FOOTER_HEIGHT = 54
FRIEND_IMAGE_HEIGHT = FRIEND_CARD_HEIGHT - FRIEND_FOOTER_HEIGHT
FRIEND_GRID_COLUMNS = 3
OUTER_MARGIN = 8
COLUMN_GAP = 8
CENTER_MIN_WIDTH = 320
PRESET_PANEL_MIN = 280
INSTANCE_BAR_HEIGHT = 36
WINDOW_HEIGHT = 532
WINDOW_HEIGHT_WITH_INSTANCE = WINDOW_HEIGHT + INSTANCE_BAR_HEIGHT + 6
LEFT_COLUMN_WIDTH = FRIENDS_PANEL_WIDTH
RIGHT_COLUMN_WIDTH = PREVIEW_PANEL_WIDTH

def compute_window_width(*, show_left: bool, show_right: bool, show_center: bool=True) -> int:
    width = OUTER_MARGIN * 2
    if show_left:
        width += LEFT_COLUMN_WIDTH + COLUMN_GAP
    if show_center:
        width += CENTER_MIN_WIDTH
        if show_right:
            width += COLUMN_GAP + RIGHT_COLUMN_WIDTH
    elif show_right:
        width += RIGHT_COLUMN_WIDTH
    return max(width, 360)
